### ISSUE TITLE
Slash Commands Roadmap

### ISSUE THREAD

**Issue by Kalissaac** [SchwaIndustries/ScrimBot#23]
[Slash commands are here](https://discord.com/developers/docs/interactions/slash-commands), and I think they'll be very useful for ScrimBot. To implement them, we'll need to do a lot of refactoring though since most code relies upon user messages and incremental data-gathering, both of which don't apply to slash commands. Here's the general requirements that we need to achieve before slash commands are production-ready:

- [ ] Slash Command JSON (the data that needs to be sent to Discord to register the commands)
- [ ] Match commands (create, edit, info, start, score, cancel)
- [ ] User commands (info, edit, register)
- [ ] Should user commands be shown when executed or deleted?

**Comment by MomoMiles** [comment]
What is the status on this?

**Comment by Kalissaac** [comment]
This is being implemented in the `golang` branch.
